const mongoose = require('mongoose');
// Stores the payment related information for each J4U user. Card details apart from teh cardType are never stored in Azure DB for security purpose
var customerIdSchema = mongoose.Schema({
	// unique id for a customer that safeway J4U login provides
	'GUID': {
		type: String,
		required: true
	},
	// unique customer id generated by First Data
	'fdCustomerId': {
		type: String,
		required: false
	},
	// Determines if the user is blocked as a result of violating any of the fraud rules 
	'userBlocked': {
		type: Boolean,
		required: false
	},
	// Stores the fdAccountId for the selected card in wallet and uses this card by default for transactions
	'defaultCard': {
		type: String,
		required: false
	},
	// stores the time when a card was added in every 24hrs in timestamp format to handle logic for 24 hr fraud rule limit
	'addCardTime': {
		type: Number,
		required: false
	},
	// stores the number of cards added in 24hrs to help build logic for 24hr rule limit
	'cardCounter': {
		type: Number,
		required: false
	}
});

const CustomerId = mongoose.model('CustomerId', customerIdSchema);
module.exports = CustomerId;
